/**
 * Postgres AI Insights hook.
 *
 * The Postgres analog of `use-insights.ts`, keyed by an env-based `pgHostId`
 * (index into the `POSTGRES_*` lists — the same id the agent tools and cron
 * sweep use). Reads cards from GET /api/v1/insights/postgres, auto-generates
 * once per source on mount (respecting the server throttle), filters
 * user-dismissed cards (shared localStorage, engine-prefixed keys), and exposes
 * dismiss / refresh / generate. Deliberately leaner than `useInsights` — no
 * per-user settings, model picker, or localStorage cache.
 */

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'

import type { InsightCard } from '@/lib/insights/types'

import { useCallback, useEffect, useMemo, useRef } from 'react'
import {
  dismissAllInsights,
  dismissInsight,
  filterActiveInsights,
} from '@/lib/insights/dismissed-insights'
import { apiFetch } from '@/lib/swr/api-fetch'
import { REFRESH_INTERVAL, visibilityAwareInterval } from '@/lib/swr/config'

interface InsightsResponse {
  insights: InsightCard[]
  count: number
  disabled?: boolean
}

export interface UsePostgresInsightsResult {
  readonly insights: readonly InsightCard[]
  readonly counts: { critical: number; warning: number; info: number }
  isLoading: boolean
  isGenerating: boolean
  refresh: () => void
  generate: () => void
  dismiss: (insight: InsightCard) => void
  dismissAll: () => void
}

export function usePostgresInsights(
  pgHostId: number
): UsePostgresInsightsResult {
  const queryClient = useQueryClient()
  const queryKey = useMemo(
    () => [`/api/v1/insights/postgres`, pgHostId],
    [pgHostId]
  )

  const { data, isLoading } = useQuery<InsightsResponse>({
    queryKey,
    queryFn: async () => {
      const res = await apiFetch(
        `/api/v1/insights/postgres?pg=${encodeURIComponent(String(pgHostId))}`
      )
      if (!res.ok) throw new Error('Failed to fetch Postgres insights')
      return res.json()
    },
    refetchInterval: visibilityAwareInterval(REFRESH_INTERVAL.SLOW_2M),
    staleTime: 60_000,
    retry: 1,
  })

  const invalidate = useCallback(
    () => queryClient.invalidateQueries({ queryKey }),
    [queryClient, queryKey]
  )

  const generateMutation = useMutation({
    mutationFn: async ({
      force = true,
    }: {
      force?: boolean
    } = {}): Promise<InsightsResponse> => {
      const params = new URLSearchParams({ pg: String(pgHostId) })
      if (force) params.set('force', 'true')
      else params.set('enrich', 'false')
      const res = await apiFetch(
        `/api/v1/insights/postgres?${params.toString()}`,
        { method: 'POST' }
      )
      if (!res.ok) throw new Error('Failed to generate Postgres insights')
      return res.json()
    },
    onSuccess: () => invalidate(),
  })

  const merged = useMemo(() => {
    const byKey = new Map<string, InsightCard>()
    for (const i of data?.insights ?? []) byKey.set(i.key, i)
    return Array.from(byKey.values())
  }, [data])

  const insights = filterActiveInsights(merged)

  // Auto-generate once per source per session when nothing is stored, so the
  // panel populates on load. Respects the server throttle (force:false).
  const autoGenerated = useRef<Set<number>>(new Set())
  useEffect(() => {
    if (isLoading || generateMutation.isPending) return
    if (data?.disabled) return
    if (merged.length > 0) return
    if (autoGenerated.current.has(pgHostId)) return
    autoGenerated.current.add(pgHostId)
    generateMutation.mutate({ force: false })
  }, [isLoading, merged.length, pgHostId, data?.disabled, generateMutation])

  const counts = insights.reduce(
    (acc, i) => {
      acc[i.severity] += 1
      return acc
    },
    { critical: 0, warning: 0, info: 0 }
  )

  const dismiss = useCallback(
    (insight: InsightCard) => {
      dismissInsight(insight)
      invalidate()
    },
    [invalidate]
  )

  const dismissAll = useCallback(() => {
    dismissAllInsights(insights)
    invalidate()
  }, [insights, invalidate])

  return {
    insights,
    counts,
    isLoading,
    isGenerating: generateMutation.isPending,
    refresh: invalidate,
    generate: () => generateMutation.mutate({ force: true }),
    dismiss,
    dismissAll,
  }
}
