import {
  rehypeCodeDefaultOptions,
  remarkMdxMermaid,
} from 'fumadocs-core/mdx-plugins'
import { defineConfig, defineDocs } from 'fumadocs-mdx/config'
import { transformerTwoslash } from 'fumadocs-twoslash'

// Content is generated by scripts/sync-docs.mjs from ../../docs/content/** (the
// committed source of truth). The generated content/docs/** directory is gitignored.
export const docs = defineDocs({
  dir: 'content/docs',
  docs: {
    postprocess: {
      includeProcessedMarkdown: true,
    },
  },
})

export default defineConfig({
  mdxOptions: {
    remarkPlugins: [remarkMdxMermaid],
    // Third-party deploy badges (e.g. vercel.com/button,
    // deploy.workers.cloudflare.com/button) are remote images referenced from
    // MDX. remark-image fetches every remote image at build time to compute
    // its dimensions by default — a single timeout on the badge host fails
    // the whole docs build. Disable that external size lookup so the build
    // never depends on third-party image host availability (#2462).
    remarkImageOptions: {
      external: false,
    },
    rehypeCodeOptions: {
      // Spread the defaults first so required options (e.g. `themes`) are kept.
      ...rehypeCodeDefaultOptions,
      // Twoslash generates popup annotations for inner code snippets (e.g.
      // inferred types shown in hover panels).  Shiki does not lazy-load langs
      // for those snippets, so every language that can appear in a twoslash
      // popup must be listed here explicitly.
      langs: ['ts', 'tsx', 'js', 'jsx'],
      transformers: [
        // Keep the default transformers (icon + tab) first.
        ...(rehypeCodeDefaultOptions.transformers ?? []),
        // Twoslash: runs at build time, annotates TypeScript code blocks.
        transformerTwoslash(),
      ],
    },
  },
})
